version: '3.8'

services:
  waha:
    container_name: waha
    image: devlikeapro/whatsapp-http-api
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080" 
    env_file:
      - .env
    volumes:
      - ./tokens:/app/tokens
      - ./files:/app/files 